title: Josiah Witt
author: Josiah Witt
email: josiah@witt.life
description: Software Engineer
url: "https://josiahwitt.com"
permalink: date

markdown: kramdown
exclude: ["README.md", "signed_posts", "sign", "sign-all", "verify-all-signed"]
